## Popsy Nails & Mehendi

theme: Jekyll Themes
title: Welcome to Popsy Nails & Mehendi!
description: Feel free to bookmark this to keep an eye on my project updates

### Markdown
Henna & Nail Salon in Bellevue
Opening at 4PM

Markdown is a lightweight and easy-to-use syntax for styling your writing. It includes conventions for

```markdown
Syntax highlighted code block

# Header 1
View Menu
## Header 2
Updates
### Header 3
About Me & Popsy Nails Mehendi

- Bulleted
- List

1. Numbered
2. List

**Bold** and _Italic_ and `Code` text

[Link](url) and ![Image](src)
```

For more details see [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/).

### Jekyll Themes

Your Pages site will use the layout and styles from the Jekyll theme you have selected in your [repository settings](https://github.com/anwyannie11/anwyannie11.github.io/settings). The name of this theme is saved in the Jekyll `_config.yml` configuration file.

### Support or Contact

Having trouble with Pages? Check out our [documentation](https://help.github.com/categories/github-pages-basics/) or [contact support](https://github.com/contact) and we’ll help you sort it out.
